spring:
  application:
    name: talento_tech_proyecto
    security:
      jwt:
        #        secret-key: { JWT_SECRET_KEY }
        secret-key: ${JWT_SECRET_KEY}
        expiration: 86400000
        refresh-token:
          expiration: 604800000
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # o 'create', 'create-drop', 'validate', 'none'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true